name: flaguru
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  firebase_core: ^0.4.0+1
  firebase_analytics: ^4.0.2
  firebase_auth: ^0.11.1+3
  cloud_firestore: 0.12.9+5
  google_sign_in: ^4.0.7
  flutter_spinkit: "^4.0.0"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/database/flaguru.db
   - assets/images/flag-of-Afghanistan.png
   - assets/images/flag-of-Albania.png
   - assets/images/flag-of-Algeria.png
   - assets/images/flag-of-Andorra.png
   - assets/images/flag-of-Angola.png
   - assets/images/flag-of-Antigua.png
   - assets/images/flag-of-Argentina.png
   - assets/images/flag-of-Armenia.png
   - assets/images/flag-of-Australia.png
   - assets/images/flag-of-Austria.png
   - assets/images/flag-of-Azerbaijan.png
   - assets/images/flag-of-Bahamas.png
   - assets/images/flag-of-Bahrain.png
   - assets/images/flag-of-Bangladesh.png
   - assets/images/flag-of-Barbados.png
   - assets/images/flag-of-Belarus.png
   - assets/images/flag-of-Belgium.png
   - assets/images/flag-of-Belize.png
   - assets/images/flag-of-Benin.png
   - assets/images/flag-of-Bhutan.png
   - assets/images/flag-of-Bolivia.png
   - assets/images/flag-of-Bosnia-Herzegovina.png
   - assets/images/flag-of-Botswana.png
   - assets/images/flag-of-Brazil.png
   - assets/images/flag-of-Brunei.png
   - assets/images/flag-of-Bulgaria.png
   - assets/images/flag-of-Burkina-Faso.png
   - assets/images/flag-of-Burundi.png
   - assets/images/flag-of-Cabo-Verde.png
   - assets/images/flag-of-Cambodia.png
   - assets/images/flag-of-Cameroon.png
   - assets/images/flag-of-Canada.png
   - assets/images/flag-of-Central-African-Republic.png
   - assets/images/flag-of-Chad.png
   - assets/images/flag-of-Chile.png
   - assets/images/flag-of-China.png
   - assets/images/flag-of-Colombia.png
   - assets/images/flag-of-Comoros.png
   - assets/images/flag-of-Congo-Democratic-Republic-of.png
   - assets/images/flag-of-Congo.png
   - assets/images/flag-of-Costa-Rica.png
   - assets/images/flag-of-Cote-d-Ivoire.png
   - assets/images/flag-of-Croatia.png
   - assets/images/flag-of-Cuba.png
   - assets/images/flag-of-Cyprus.png
   - assets/images/flag-of-Czech-Republic.png
   - assets/images/flag-of-Denmark.png
   - assets/images/flag-of-Djibouti.png
   - assets/images/flag-of-Dominica.png
   - assets/images/flag-of-Dominican-Republic.png
   - assets/images/flag-of-Ecuador.png
   - assets/images/flag-of-Egypt.png
   - assets/images/flag-of-El-Salvador.png
   - assets/images/flag-of-Equatorial-Guinea.png
   - assets/images/flag-of-Eritrea.png
   - assets/images/flag-of-Estonia.png
   - assets/images/flag-of-Eswatini.png
   - assets/images/flag-of-Ethiopia.png
   - assets/images/flag-of-Fiji.png
   - assets/images/flag-of-Finland.png
   - assets/images/flag-of-France.png
   - assets/images/flag-of-Gabon.png
   - assets/images/flag-of-Gambia.png
   - assets/images/flag-of-Georgia.png
   - assets/images/flag-of-Germany.png
   - assets/images/flag-of-Ghana.png
   - assets/images/flag-of-Greece.png
   - assets/images/flag-of-Grenada.png
   - assets/images/flag-of-Guatemala.png
   - assets/images/flag-of-Guinea-Bissau.png
   - assets/images/flag-of-Guinea.png
   - assets/images/flag-of-Guyana.png
   - assets/images/flag-of-Haiti.png
   - assets/images/flag-of-Honduras.png
   - assets/images/flag-of-Hungary.png
   - assets/images/flag-of-Iceland.png
   - assets/images/flag-of-India.png
   - assets/images/flag-of-Indonesia.png
   - assets/images/flag-of-Iran.png
   - assets/images/flag-of-Iraq.png
   - assets/images/flag-of-Ireland.png
   - assets/images/flag-of-Israel.png
   - assets/images/flag-of-Italy.png
   - assets/images/flag-of-Jamaica.png
   - assets/images/flag-of-Japan.png
   - assets/images/flag-of-Jordan.png
   - assets/images/flag-of-Kazakhstan.png
   - assets/images/flag-of-Kenya.png
   - assets/images/flag-of-Kiribati.png
   - assets/images/flag-of-Korea-North.png
   - assets/images/flag-of-Korea-South.png
   - assets/images/flag-of-Kosovo.png
   - assets/images/flag-of-Kuwait.png
   - assets/images/flag-of-Kyrgyzstan.png
   - assets/images/flag-of-Laos.png
   - assets/images/flag-of-Latvia.png
   - assets/images/flag-of-Lebanon.png
   - assets/images/flag-of-Lesotho.png
   - assets/images/flag-of-Liberia.png
   - assets/images/flag-of-Libya.png
   - assets/images/flag-of-Liechtenstein.png
   - assets/images/flag-of-Lithuania.png
   - assets/images/flag-of-Luxembourg.png
   - assets/images/flag-of-Madagascar.png
   - assets/images/flag-of-Malawi.png
   - assets/images/flag-of-Malaysia.png
   - assets/images/flag-of-Maldives.png
   - assets/images/flag-of-Mali.png
   - assets/images/flag-of-Malta.png
   - assets/images/flag-of-Marshall-Islands.png
   - assets/images/flag-of-Mauritania.png
   - assets/images/flag-of-Mauritius.png
   - assets/images/flag-of-Mexico.png
   - assets/images/flag-of-Micronesia.png
   - assets/images/flag-of-Moldova.png
   - assets/images/flag-of-Monaco.png
   - assets/images/flag-of-Mongolia.png
   - assets/images/flag-of-Montenegro.png
   - assets/images/flag-of-Morocco.png
   - assets/images/flag-of-Mozambique.png
   - assets/images/flag-of-Myanmar.png
   - assets/images/flag-of-Namibia.png
   - assets/images/flag-of-Nauru.png
   - assets/images/flag-of-Nepal.png
   - assets/images/flag-of-Netherlands.png
   - assets/images/flag-of-New-Zealand.png
   - assets/images/flag-of-Nicaragua.png
   - assets/images/flag-of-Niger.png
   - assets/images/flag-of-Nigeria.png
   - assets/images/flag-of-North-Macedonia.png
   - assets/images/flag-of-Norway.png
   - assets/images/flag-of-Oman.png
   - assets/images/flag-of-Pakistan.png
   - assets/images/flag-of-Palau.png
   - assets/images/flag-of-Palestine.png
   - assets/images/flag-of-Panama.png
   - assets/images/flag-of-Papua-New-Guinea.png
   - assets/images/flag-of-Paraguay.png
   - assets/images/flag-of-Peru.png
   - assets/images/flag-of-Philippines.png
   - assets/images/flag-of-Poland.png
   - assets/images/flag-of-Portugal.png
   - assets/images/flag-of-Qatar.png
   - assets/images/flag-of-Romania.png
   - assets/images/flag-of-Russia.png
   - assets/images/flag-of-Rwanda.png
   - assets/images/flag-of-Samoa.png
   - assets/images/flag-of-San-Marino.png
   - assets/images/flag-of-Sao-Tome-and-Principe.png
   - assets/images/flag-of-Saudi-Arabia.png
   - assets/images/flag-of-Senegal.png
   - assets/images/flag-of-Serbia.png
   - assets/images/flag-of-Seychelles.png
   - assets/images/flag-of-Sierra-Leone.png
   - assets/images/flag-of-Singapore.png
   - assets/images/flag-of-Slovakia.png
   - assets/images/flag-of-Slovenia.png
   - assets/images/flag-of-Solomon-Islands.png
   - assets/images/flag-of-Somalia.png
   - assets/images/flag-of-South-Africa.png
   - assets/images/flag-of-South-Sudan.png
   - assets/images/flag-of-Spain.png
   - assets/images/flag-of-Sri-Lanka.png
   - assets/images/flag-of-St-Kitts-Nevis.png
   - assets/images/flag-of-St-Lucia.png
   - assets/images/flag-of-St-Vincent-the-Grenadines.png
   - assets/images/flag-of-Sudan.png
   - assets/images/flag-of-Suriname.png
   - assets/images/flag-of-Sweden.png
   - assets/images/flag-of-Switzerland.png
   - assets/images/flag-of-Syria.png
   - assets/images/flag-of-Taiwan.png
   - assets/images/flag-of-Tajikistan.png
   - assets/images/flag-of-Tanzania.png
   - assets/images/flag-of-Thailand.png
   - assets/images/flag-of-Timor-Leste.png
   - assets/images/flag-of-Togo.png
   - assets/images/flag-of-Tonga.png
   - assets/images/flag-of-Trinidad-and-Tobago.png
   - assets/images/flag-of-Tunisia.png
   - assets/images/flag-of-Turkey.png
   - assets/images/flag-of-Turkmenistan.png
   - assets/images/flag-of-Tuvalu.png
   - assets/images/flag-of-Uganda.png
   - assets/images/flag-of-Ukraine.png
   - assets/images/flag-of-United-Arab-Emirates.png
   - assets/images/flag-of-United-Kingdom.png
   - assets/images/flag-of-United-States-of-America.png
   - assets/images/flag-of-Uruguay.png
   - assets/images/flag-of-Uzbekistan.png
   - assets/images/flag-of-Vanuatu.png
   - assets/images/flag-of-Vatican-City.png
   - assets/images/flag-of-Venezuela.png
   - assets/images/flag-of-Vietnam.png
   - assets/images/flag-of-Yemen.png
   - assets/images/flag-of-Zambia.png
   - assets/images/flag-of-Zimbabwe.png
   - assets/background/worldmap.jpg
   - assets/background/background_menu_screen.gif
   - assets/icon/search.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
    - family:  Menu_Icon
      fonts:
        - asset: assets/fonts/Menu_Icon.ttf